CHANGELOG.md
source/skins/simple/SwitchSkin.js
source/skins/simple/identifiers.js
source/themes/simple/SimpleSwitch.scss
stories/Switch.stories.js
stories/index.js

This PR adds a `SwitchSkin` which can be used with the `Checkbox` logic to render a switch:

[DAEF-346] add switch skin for checkbox component

---

CHANGELOG.md
source/skins/simple/TextAreaSkin.js
source/themes/simple/SimpleFormField.scss
source/themes/simple/SimpleTextArea.scss

This PR introduces a fix which prevents CSS-class inheritance on TextAreaSkin textarea element.
When passing `className` property to Textarea component it should be consumed only by TextAreaSkin's top level element which is a `FormFieldSkin`.

Fix/daef 349 Fix react-polymorph Textarea component CSS-class inheritance bug

---

package.json
source/components/Modal.js
source/skins/simple/ModalSkin.js
source/skins/simple/identifiers.js
source/themes/simple/SimpleModal.scss
stories/Modal.stories.js
stories/Modal.stories.scss
stories/index.js

This PR introduces a simple modal dialog component based on [react-modal](https://reactcommunity.org/react-modal/) (instead of react-polymorph, which is way too complicated for our needs):
**NOTE:** This component is very basic and does not support any kind of special functionality apart from the usual modal (close on overlay click etc.). All the "actions" like button clicks simply have to be defined by the using application … which makes more sense anyway because the requirements for the dialogs are very app specific anyway.

[DAEF-342] adds basic modal dialog component

---

CHANGELOG.md
source/components/Select.js
source/skins/simple/FormFieldSkin.js

This PR makes dropdowns toggle their open state on label clicks, instead of only opening (but not closing) as described in https://issues.serokell.io/issue/DAEF-480.
I could not reproduce the second issue (small lag/delay on first open) on my machine. I won't spend more time on that since it's not a critical bug (and i can't fix it here).

[DAEF-480] toggle dropdown on label clicks

---

CHANGELOG.md
source/components/Checkbox.js
source/components/FormField.js
source/utils/props.js
stories/Checkbox.stories.js

This PR improves the prop types used for `label` property in various components to also allow React elements in addition to strings:
Before this triggered a prop types error.

[DAEF-488] allow react elements as checkbox and form field labels

---

CHANGELOG.md
source/skins/simple/AutocompleteSkin.js
source/skins/simple/OptionsSkin.js
source/skins/simple/SelectSkin.js
source/skins/simple/raw/AutocompleteSkin.js
source/skins/simple/raw/OptionsSkin.js
source/skins/simple/raw/SelectSkin.js
source/themes/simple/SimpleBubble.scss
source/themes/simple/SimpleInput.scss
source/themes/simple/SimpleOptions.scss
source/themes/simple/SimpleSelect.scss

This PR fixes an issue with the way the `OptionsSkin` was included in the `SelectSkin` component which resulted in non-configurable styles, since always the default theme was chosen instead of the raw / configurable version.

[DDW-91] fix broken styling for options bubble within select component

---

CHANGELOG.md
source/components/Bubble.js
source/components/Options.js
source/components/Tooltip.js
source/skins/simple/raw/BubbleSkin.js
source/skins/simple/raw/OptionsSkin.js
source/skins/simple/raw/TooltipSkin.js
source/themes/simple/SimpleBubble.scss
source/themes/simple/SimpleInput.scss
source/themes/simple/SimpleOptions.scss
stories/Bubble.stories.js
stories/Bubble.stories.scss

This PR fixes the positioning logic of the select/autocomplete options that was accidentally removed when the bubble component was introduced. I also added a simple story for the bubble to showcase the "floating over the other content" state that is used in certain situations.
This also fixes the issues we have been seeing in Daedalus dialogs:

[DDW-98] fix bubble and options positioning logic

---

CHANGELOG.md
source/themes/simple/SimpleAutocomplete.scss

This PR introduces a small fix for `Autocomplete` component styling. There was `border-radius` CSS property missing.

Fix/ddw 111 Fix Autocomplete component styling

---

CHANGELOG.md
source/components/Autocomplete.js
stories/Autocomplete.stories.js

This PR adds two missing features to the Autocomplete component:
1. it exposes `clear()` method which is to be used to clear `selectedOptions`
2. it introduces `pre-selection` by picking up `selectedOptions` property on initial component rendering.

Feature/ddw 185 Add Autocomplete clear feature

---

CHANGELOG.md
source/components/Options.js
source/skins/simple/raw/OptionsSkin.js
source/skins/simple/raw/SelectSkin.js
source/themes/simple/SimpleCheckbox.scss
source/themes/simple/SimpleOptions.scss

This PR adds the feature of showing a checkmark for the selected option in a `Select` component:

Feature/ddw 225 Show checkmark for selected option

---

CHANGELOG.md
source/components/Options.js
source/skins/simple/OptionsSkin.js
source/themes/simple/SimpleOptions.scss
source/themes/simple/SimpleSelect.scss
stories/Select.stories.js

This PR fixes broken positioning of the selected option checkmark for right-to-left screens (e.g: Arabic).
Before:
After:

fix broken select checkmark positioning for right-to-left screens

---

CHANGELOG.md
__tests__/__snapshots__/TextArea.test.js.snap
source/components/FormField.js
source/components/Input.js
source/components/NumericInput.js
source/components/Select.js
source/components/TextArea.js
source/skins/simple/AutocompleteSkin.js
source/skins/simple/FormFieldSkin.js
source/skins/simple/InputSkin.js
source/skins/simple/TextAreaSkin.js
stories/Autocomplete.stories.js
stories/Input.stories.js
stories/NumericInput.stories.js
stories/Select.stories.js
stories/TextArea.stories.js

- This PR wraps TextAreaSkin's render method in FormField so labels and errors are rendered the same as in Input and NumericInput. 
- Fixes Input, NumericInput, and TextArea components so they pass a prop called inputRef or textareaRef to FormField in their skins. This properly makes use of React v16.3.1+'s ref API instead of using the onRef callback.
- Adds autoFocus, onBlur, and onFocus props to NumericInput and TextArea

[DDW-336] fix refs for input components in react polymorph

---

CHANGELOG.md
source/themes/simple/SimpleTextArea.scss

This PR fixes the same issue as #71 for textareas ;)

[DDW-352] show red error state border also around focused textareas

---

CHANGELOG.md
source/components/HOC/ThemeContext.js
source/components/ThemeProvider.js
source/themes/API/autocomplete.js
source/themes/API/bubble.js
source/themes/API/button.js
source/themes/API/checkbox.js
source/themes/API/formfield.js
source/themes/API/index.js
source/themes/API/input.js
source/themes/API/modal.js
source/themes/API/options.js
source/themes/API/radio.js
source/themes/API/select.js
source/themes/API/switch.js
source/themes/API/textarea.js
source/themes/API/toggler.js
source/themes/API/tooltip.js
source/themes/simple/index.js
stories/Select.stories.js
stories/ThemeProvider.stories.js
stories/Tooltip.stories.js

- This PR replaces all default exports in the theme directory with constants and exports them.
- This allows each component's theme API object to be imported as a named import. This change reduces file size and clutter within `themes/API/index.js` and `themes/simple/index.js`.
- Puts `SimpleTheme` and `ROOT_THEME_API` properties in ABC order and defines properties using `IDENTIFIERS`.
- In `HOC/ThemeContext.js` the import statements for each component's theme file are removed along with the reconstructed `SimpleTheme` object that's passed to `defaultContext`. `SimpleTheme` is now imported as a constant and passed to `defaultContext,` reducing file size and improving readability.

Improve theme exports

---

__tests__/Autocomplete.behavior.test.js
__tests__/Autocomplete.test.js
__tests__/Bubble.test.js
__tests__/Button.test.js
__tests__/Checkbox.test.js
__tests__/FormField.test.js
__tests__/Input.test.js
__tests__/NumericInput.behavior.test.js
__tests__/NumericInput.test.js
__tests__/Options.test.js
__tests__/Radio.test.js
__tests__/Select.test.js
__tests__/Switch.test.js
__tests__/TextArea.test.js
__tests__/Toggler.test.js
__tests__/helpers/theming.js
source/components/HOC/ThemeContext.js

This PR removes the reference to `SimpleTheme` as default and uses an empty theme object by default now. This caused the tests to fail since they are written with the assumption of having a theme applied.
That's why i introduced some simple test helpers (`renderInSimpleTheme` and `mountInSimpleTheme`) that render/mount the test markup wrapped in `ThemeProvider` configured with the `SimpleTheme`.
(@MarcusHurney in case you wonder why i split up the Autocomplete and NumericInput tests into two separate files [one for snapshots and one for behavior tests] … it's because of this issue i ran into: https://github.com/facebook/react/issues/13150)
Since that separation kind of makes sense anyway (those test files became too large already) … i thought it's an easy solution for now, until that fix …

[DDW-367] use empty theme as default to avoid duplicated styles

---

CHANGELOG.md
source/components/Header.js
source/skins/simple/HeaderSkin.js
source/themes/API/header.js
source/themes/API/index.js
source/themes/simple/SimpleHeader.scss
source/themes/simple/index.js
stories/Header.stories.js
stories/Header.stories.scss
stories/index.js
stories/theme-customizations/Header.custom.scss
stories/theme-overrides/customHeader.scss

This PR adds a Header component for creating 4 unique instances of a themed Header and makes them available in context as part of SimpleTheme. Theme variation and manipulation of specific styles can be accessed via props passed to Header as booleans. Combining and composing variations of these props with a theme makes the visual rendering of Header flexible and convenient.

[DDW-197] create header component

---

CHANGELOG.md
source/components/Header.js
source/components/layout/Base.js
source/components/layout/Flex.js
source/components/layout/FlexItem.js
source/themes/API/flex.js
source/themes/API/index.js
source/themes/simple/SimpleFlex.scss
source/themes/simple/index.js
source/utils/layout.js
stories/Layout.stories.js
stories/Layout.stories.scss
stories/index.js
stories/theme-overrides/customFlex.scss

This PR adds layout components Flex and FlexItem. This abstracts layout into composable, compound components that facilitate a more uniform and reusable layout solution. Enables third party developers using react-polymorph to craft applications with uniformity of layout specs and style more easily with most of the Flexbox API.

[DDW-197] create flex layout component

---

CHANGELOG.md
source/components/Autocomplete.js
source/components/Bubble.js
source/components/Button.js
source/components/Checkbox.js
source/components/FormField.js
source/components/Header.js
source/components/InfiniteScroll.js
source/components/Input.js
source/components/LoadingSpinner.js
source/components/Modal.js
source/components/NumericInput.js
source/components/Options.js
source/components/ProgressBar.js
source/components/Radio.js
source/components/Select.js
source/components/TextArea.js
source/components/ThemeProvider.js
source/components/Tooltip.js
source/components/layout/Flex.js
source/components/layout/Grid.js
source/components/layout/Gutter.js
source/utils/props.js
source/utils/themes.js
stories/ThemeProvider.stories.js
stories/theme-overrides/buttonOverrides.scss
stories/theme-overrides/checkboxOverrides.scss
stories/theme-overrides/progressBarOverrides.scss

This PR fixes a bug where `ThemeProvider` failed to compose its `theme` prop with the user's custom styles passed as a `themeOverrides` prop. 
Adds a `themeOverrides` story to `ThemeProvider.stories.js` to exemplify intended behavior and show the bug is corrected.

[DDW-381] Fix themeOverrides in react polymorph ThemeProvider

---

CHANGELOG.md
source/components/Autocomplete.js
source/components/Bubble.js
source/components/Button.js
source/components/Checkbox.js
source/components/FormField.js
source/components/HOC/GlobalListeners.js
source/components/HOC/withTheme.js
source/components/Input.js
source/components/LoadingSpinner.js
source/components/Modal.js
source/components/NumericInput.js
source/components/Options.js
source/components/ProgressBar.js
source/components/Radio.js
source/components/Select.js
source/components/TextArea.js
source/components/ThemeProvider.js
source/components/Tooltip.js
source/components/layout/Flex.js
source/components/layout/FlexItem.js
source/utils/props.js

This PR adds a `displayName` static property to all components for semantic convenience when using react developer tools and for targeting a component by its `displayName` in tests.

[DDW-446] Add display name to components

---

CHANGELOG.md
__tests__/NumericInput.behavior.test.js
source/components/NumericInput.js
stories/NumericInput.stories.js

- Fixes `NumericInput`'s value processing logic to only return the integer numbers before the decimal when `maxAfterDot={0}`.
- Adds one new behavior test for `NumericInput` which tests `maxAfterDot={0}`.
- Adds one new story for `NumericInput` which shows intended behavior when `maxAfterDot={0}`.
----------------------------------------------------------------------------------------------------

[DDW-375] Adjust NumericInput maxAfterDot Config

---

CHANGELOG.md
source/components/NumericInput.js

This PR fixes two bugs in the `NumericInput` component.
1. The first fix addresses the scenario when a user enters numerical digits and then presses `.`. The cursor should move right to the decimal digits, but this intended behavior does not happen when a user enters exactly 4 digits and then presses `.`. It needs an additional press of `.` to move right. 
2. The second fix addresses the scenario when a user enters `ctrl-A` + `del` on an amount being displayed in `NumericInput`, then enters a new amount. The new amount's digits are not in the correct order. For example, the user presses `12345` and gets `23451`.

[DDW-488] Fix NumericInput Carrot Malfunction

---

CHANGELOG.md
package.json
source/components/Checkbox.js
yarn.lock

- Updates packages that were found to be vulnerable by the automatic Github security audit which include: `lodash`, `babel-plugin-lodash`, and `node-sass`.
- Fixes a bug found discovered in the `Toggler` and `Switch` stories where the `Checkbox` component was choosing `CheckboxSkin` from context and rendering it in situations where a `skin` prop isn't passed to `Checkbox`. 
In situations where `this.props.skin` is undefined, the fix in this PR ensures that `Checkbox` first looks for a skin in context using `context.skins[this.props.themeId]`. By using `this.props.themeId` as the search key, `CheckboxSkin` will still be rendered as the default if neither a `themeId` nor a `skin` are passed as props because `this.props.themeId` has a default value set: `static defaultProps = { themeId: …

Update Vulnerable Dependencies and Fix Checkbox Bug

---

CHANGELOG.md
__tests__/__snapshots__/Autocomplete.test.js.snap
__tests__/__snapshots__/Options.test.js.snap
__tests__/__snapshots__/Select.test.js.snap
source/components/Autocomplete.js
source/components/Bubble.js
source/components/FormField.js
source/components/HOC/GlobalListeners.js
source/components/Options.js
source/components/Select.js
source/skins/simple/AutocompleteSkin.js
source/skins/simple/BubbleSkin.js
source/skins/simple/InfiniteScrollSkin.js
source/skins/simple/InputSkin.js
source/skins/simple/OptionsSkin.js
source/skins/simple/SelectSkin.js
source/skins/simple/TextAreaSkin.js
source/themes/simple/SimpleOptions.scss
stories/ThemeProvider.stories.js

**1.** This PR ensures that the maximum height of the `Options` dropdown is calculated based on `window.innerHeight` and the distance in pixels from the `top` or `bottom` of `Options` to the top or bottom of the user's viewport. This ensures that the drop down doesn't run off the screen when there are many options that have a greater height than `window.innerHeight`. The `max-height` for `Options` is recalculated during `scroll` and `resize` events.
**2.** This PR also fixes the flow types for refs that are passed as props between components and skins. We should have been using the flow type `ElementRef` instead of `Ref`, so the changes here make this swap.
**How to Test**
In order to test these changes, I recommend running `yarn storybook` and navigating to the `ThemeProvider` stories …

[DDW-609] Fix Options Drop Down Max Height for Small Screens

---

CHANGELOG.md
package.json
yarn.lock

**Please merge PR 102 into develop before this one, so I can pull the changes into here before we merge this one and cut a new release.**
This PR upgrades `react`, `react-dom`, and `react-test-renderer` to version `16.8.6`. This addresses the Github warning generated regarding `react-dom` which says:

Upgrade react-dom to Address Github Vulnerability Warning

---

CHANGELOG.md
source/themes/simple/SimpleButton.scss
stories/ThemeProvider.stories.js

Adds CSS variable in `SimpleButton.scss` allowing configuration of button text color when button state is `disabled`. This is needed in Daedalus for the new theme utility function and also makes sense to have here in general.
Cleans up commented out code, unused imports, and margins that were overlooked in the changes from PR 102 (added dynamic sizing of Options `max-height`).

[DDW-604] Add Disabled Text Color CSS Var for Simple Button

---

CHANGELOG.md
source/components/NumericInput.js
source/utils/strings.js

This PR fixes the bug described in #98 (see there how to test this)
I wasn't able to write a proper test for this in Jest / Enzyme since it's very hard to test keyboard inputs with controlled components without having your head explode or writing hundreds of lines of code 😢 this would be much easier with webdriver … maybe we should consider introducing real ui tests too for more complex cases like this.

[DDW-653] Fix decimal point bug in numeric input

---

CHANGELOG.md
__tests__/Select.test.js
__tests__/Stepper.test.js
__tests__/__snapshots__/Select.test.js.snap
__tests__/__snapshots__/Stepper.test.js.snap
source/components/Input.js
source/components/Select.js
source/components/Stepper.js
source/components/index.js
source/skins/simple/InputSkin.js
source/skins/simple/SelectSkin.js
source/skins/simple/StepperSkin.js
source/skins/simple/index.js
source/themes/API/index.js
source/themes/API/stepper.js
source/themes/simple/SimpleInput.scss
source/themes/simple/SimpleSelect.scss
source/themes/simple/SimpleStepper.scss
source/themes/simple/index.js
stories/Select.stories.js
stories/Select.stories.scss
stories/Stepper.stories.js
stories/index.js
stories/theme-customizations/Stepper.custom.scss
stories/theme-overrides/customStepper.scss

This PR introduces Custom select value renderer that can replace selected value default input rendered value. Also this PR introduces Stepper component as steps progress bar indicator.
- Custom Select value (`Select -> custom select value template`) - Select any select option and both label and value should appear as selected value
- Go to `Stepper` section and walk through different scenarios.
**Note:**  Both tests are related to https://zpl.io/aBRGAeA step 1 _"choose wallet"_ step
_Custom Select Value_
_Stepper Component_

[DDW-658] Custom select value and Stepper component

---

source/themes/simple/SimpleCheckbox.scss

Both in Yoroi and in Daedalus, any area in the screen to the right of a checkbox triggers a toggle on-click. 
This is because the width of checkbox root expands to fit the space

[bugfix] Use fit-content on checkbox

---

CHANGELOG.md
README.md
source/components/Bubble.js
source/components/Tooltip.js
source/skins/simple/BubbleSkin.js
source/skins/simple/TooltipSkin.js
source/themes/simple/SimpleBubble.scss
source/themes/simple/SimpleOptions.scss
source/themes/simple/mixins/arrow.scss
stories/Tooltip.stories.js
stories/Tooltip.stories.scss
stories/theme-customizations/Bubble.custom.scss
stories/theme-overrides/customBubble.scss

For Yoroi, our designer wants the following UI:
where the pop-up and underline appear on-hover.
This requires the following two changes
The current behavior in React-Polymorph is to center the arrow on the content. Since addresses are really long, this ends up looking like this
The current hack for displaying an arrow didn't allow for width/height to be different so I instead used a different hack that allows for this. I made the change background compatible so it should look pixel-for-pixel equivalent to the current implementation.

Improve tooltip

---

.eslintrc
.travis.yaml
CHANGELOG.md
README.md
__tests__/NumericInput.behavior.test.js
source/components/NumericInput.js
source/utils/types.js
stories/NumericInput.stories.js

This PR rewrites and simplifies the logic of the `NumericInput` component.
Fixes #112 and fixes #51
- `value` must be a number and `onChange` also returns numbers (not strings) now
- All formatting configuration is now handled with the prop `numberLocaleOptions` which are the options for [Number::toLocaleString](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString), which makes this component more standards compliant and will also allow us to implement i18n later on without too much hassle.
- The numeric input component does **not handle errors or enforce min/max values anymore** - since error messages created by the numeric input would never be useful in an localized context (and the enforced versions, which dont allow out-of-bound numbers …

[DDW-665] Rewrite numeric input logic

---

source/components/NumericInput.js
source/themes/simple/SimpleBubble.scss
source/themes/simple/SimpleOptions.scss
source/themes/simple/mixins/arrow.scss
stories/NumericInput.stories.js

This PR improves the handling of transient number inputs like:
Transformed state (the zero is added visually)
- `.` = `0.`
Parsed transient state (these are not shown but the output behaves like this)
- `.1` = `0.1`
- `1.` = `1`
This greatly improves UX while entering numbers in Daedalus (or other applications that would show errors like "this field is required" as soon as the number would be `null`)
This PR also fixes:
- Broken arrow color and borders
- Many small issues found and reported by QA
**Known and Acceptable Issues:**
If you enter a `,` in the fraction part of the number the caret will jump over one digit.
[QA Slack Channel](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1566222711246800)

[DDW-754] handle standalone fraction dot correctly

---

CHANGELOG.md
__tests__/Tooltip.test.js
__tests__/__snapshots__/Tooltip.test.js.snap
package.json
source/components/Bubble.js
source/components/PasswordInput.js
source/components/Tooltip.js
source/components/index.js
source/skins/simple/BubbleSkin.js
source/skins/simple/PasswordInputSkin.js
source/skins/simple/TooltipSkin.js
source/skins/simple/index.js
source/themes/API/index.js
source/themes/API/password-input.js
source/themes/API/tooltip.js
source/themes/simple/SimpleBubble.scss
source/themes/simple/SimplePasswordInput.scss
source/themes/simple/SimpleTooltip.scss
source/themes/simple/index.js
stories/Bubble.stories.js
stories/PasswordInput.stories.js
stories/PasswordInput.stories.scss
stories/Tooltip.stories.js
stories/Tooltip.stories.scss
stories/index.js

This PR implements the [designed password input](https://zpl.io/bAlyNGq) for Daedalus:
Note: This component does not implement any password score algorithm as this is very application specific. The `PasswordInput` can only be configured to display in different states:
For this it was necessary to improve the Bubble and Tooltip components to allow centered alignment without full-width. I also added stories and test cases for all of these new cases (as well as for the Tooltip component which had no tests yet).
A few minor refactorings and improvements round up the work 😉

[DDW-733] Implement password input component

---

CHANGELOG.md
source/components/Autocomplete.js
source/components/Dropdown.js
source/components/HOC/GlobalListeners.js
source/components/Options.js
source/components/Select.js
source/skins/simple/AutocompleteSkin.js
source/skins/simple/DropdownSkin.js
source/skins/simple/SelectSkin.js
stories/Dropdown.stories.js
stories/Select.stories.js

This PR introduces flexible option height and availability to pass them from parent components.

[DDW-1227] Fix options component dimensions

---

.prettierrc
source/components/Autocomplete.js
source/components/Bubble.js
source/components/Button.js
source/components/Checkbox.js
source/components/Dropdown.js
source/components/FormField.js
source/components/HOC/GlobalListeners.js
source/components/Header.js
source/components/InfiniteScroll.js
source/components/Input.js
source/components/Link.js
source/components/LoadingSpinner.js
source/components/Modal.js
source/components/NumericInput.js
source/components/Options.js
source/components/ProgressBar.js
source/components/Radio.js
source/components/ScrollBar.js
source/components/Select.js
source/components/Stepper.js
source/components/TextArea.js
source/components/ThemeProvider.js
source/components/Tooltip.js
source/components/layout/Flex.js
source/components/layout/Grid.js
source/components/layout/Gutter.js
source/utils/themes.js

Moved blocks inside `componentWillMount`, `componentWillUpdate`, and `componentWillReceiveProps` into `componentDidMount` and `componentDidUpdate` methods.

[DDW-246]: Eliminate usage of deprecated lifecycle methods

---

CHANGELOG.md
package.json
source/components/PasswordInput.js
source/skins/simple/PasswordInputSkin.js
source/themes/simple/SimplePasswordInput.scss
source/themes/simple/SimpleTooltip.scss
stories/PasswordInput.stories.js
stories/PasswordInput.stories.scss

This PR improves the password repeat feature, to simplify the integration within Daedalus.
To use an `<PasswordInput>` component for validating a repeated password it's only necessary to pass in `repeatPassword: string` and it does the rest automatically.

[DDW-170] Improve password repeat feature

---

CHANGELOG.md
package.json
yarn.lock

This PR replaces the deprecated [postinstall-build](https://www.npmjs.com/package/postinstall-build) package with the npm  `prepare` lifecycle script.

[issue-145] Remove deprecated postinstall-build package

---

CHANGELOG.md
package.json
source/components/Autocomplete.js
source/components/PasswordInput.js
source/skins/simple/AutocompleteSkin.js
source/themes/API/autocomplete.js
source/themes/simple/SimpleAutocomplete.scss
stories/Autocomplete.stories.js

This PR improves the Autocomplete `requiredSelections` prop UX with an optional `requiredSelectionsInfo` prop - a function that gets the required and actual selections as inputs and returns any string which is displayed above the autocomplete:
**Note:** The "x of x words selected" string is not generated by react-polymorph but by a callback function which can return any string for the given params like this: `(required, actual) => `${actual} words entered`
The feature consists of the combination of multiple props:
```js
maxSelections={7}
requiredSelections={[3, 5, 7]}
requiredSelectionsInfo={(required, actual) => `${actual} words entered`}
```
- `requiredSelections` contains any number of possible "target counts" of selections
- `requiredSelectionsInfo` is a callback function `(required, …

[DDW-497] Improve autocomplete required selections ux

---

.eslintrc
CHANGELOG.md
README.md
__tests__/FormField.test.js
__tests__/NumericInput.behavior.test.js
__tests__/NumericInput.test.js
__tests__/TextArea.test.js
__tests__/__snapshots__/Autocomplete.test.js.snap
__tests__/__snapshots__/FormField.test.js.snap
__tests__/__snapshots__/Input.test.js.snap
__tests__/__snapshots__/NumericInput.test.js.snap
__tests__/__snapshots__/Select.test.js.snap
__tests__/__snapshots__/TextArea.test.js.snap
jest.setup.js
package.json
source/components/FormField.js
source/components/Input.js
source/components/NumericInput.js
source/skins/simple/AutocompleteSkin.js
source/skins/simple/FormFieldSkin.js
source/skins/simple/InputSkin.js
source/skins/simple/TextAreaSkin.js
source/utils/hooks.js
source/utils/strings.js
stories/FormField.stories.js
stories/NumericInput.stories.js
yarn.lock

This PR improves the `NumericInput` component to support big numbers (bignumber.js) with "arbitrary" precision by refactoring the logic to be based on bignumber.js.
The `NumericInput` component uses the defaults/config of `BigNumber` by default which can be selectively overwritten with the following props:
```js
bigNumberFormat?: BigNumber.Format, // Will be merged with the BigNumber defaults
decimalPlaces?: number, // Only a specific number or any number of decimal places are supported (no min/max)
roundingMode?: BigNumber.RoundingMode,
value: ?BigNumber.Instance,
```
The value provided to the `NumericInput` as well as given back `onChange` are `BigNumber` instances now.
Open Storybook with the `NumericInput` component and it should work exactly like before but support any floating point …

[DDW-543] Refactor Numeric Input to use bignumber.js

---

source/components/NumericInput.js
stories/NumericInput.stories.js

Here is the definition of BigNumber.DEBUG from the documentation
```javascript
/**
* To aid in debugging, if a `BigNumber.DEBUG` property is `true` then an error will be thrown
* if the BigNumber constructor receives an invalid `BigNumber.Value`, or if `BigNumber.isBigNumber`
* receives a BigNumber instance that is malformed.
*
* ```ts
* // No error, and BigNumber NaN is returned.
* new BigNumber('blurgh')    // 'NaN'
* new BigNumber(9, 2)        // 'NaN'
* BigNumber.DEBUG = true
* new BigNumber('blurgh')    // '[BigNumber Error] Not a number'
* new BigNumber(9, 2)        // '[BigNumber Error] Not a base 2 number'
* ```
*
* An error will also be thrown if a `BigNumber.Value` is of type number with more than 15
* significant digits, as calling `toString` or `valueOf` on such numbers may …
```

Fix NumericInput on BigNumber.DEBUG

---

CHANGELOG.md
source/components/NumericInput.js
stories/NumericInput.stories.js

This PR changes the `NumericInput` component to improve the Daedalus PIN entry component UX and logic handling for PIN input fields focus, add/remove & disallowing entry of special characters. 
---
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1616408886056400)
---
**Scenario 1 - Replace a digit to unmatch the PINs**
```gherkin
Given that I am on the fourth step of the "Register for Fund3 voting" dialog
And the PIN was repeated on both fields
And the "Continue" button is enabled
When I replace one of the digits on any pin with a different value
Then I can see the "Continue" button is disabled as the values don't match
And the "Repeat" input displays an alert
```
**Scenario 2 - Insert non-numeric characters as PIN**
```gherkin
Given that I am on the fourth step …
```

[DDW-602] - Improve PIN entry component UX

---

CHANGELOG.md
source/components/NumericInput.js

This PR fixes an issue with `NumericInput` when entering numbers after having selected the decimal separator in a numeric input configured to always show a specific precision. This resulted in weird numbers being produced because the decimal separator was deleted This is now simply refused, so the number is not changed at all:
https://user-images.githubusercontent.com/172414/113428477-269ce400-93d7-11eb-9d0a-8f86888cb67b.mp4
How to test:
**Scenario 1 -  Select separator and insert a number**
```gherkin
Given that I am on the "NumericInput" Screen
And a value is inserted in the field
When I select the decimal separator on the number
And I insert a number to replace the selection
Then the decimal separator is not replaced with the value
And the cursor moves to the right of the selection
``` …

[DDW-588] Refuse inserts over decimal separator

---

source/components/Input.js

This PR fixes #165, which left an empty `createRef` without `React.createRef`. This will break any <Input /> that uses the `inputRef` prop.

Fixes broken createRef without React.

---

.yarnrc
CHANGELOG.md
source/skins/simple/OptionsSkin.js
source/themes/simple/SimpleOptions.scss

This PR fixes Select Search styles and minor code issues and it's related to Daedalus' [#2512](https://github.com/input-output-hk/daedalus/pull/2512)
* **Fixed the clear button styles:**
* **Added a `key` prop to the search highlight `em` component to fix this error:**

[DDW-645] Update react-polymorph and implement the search style variables

---

.github/workflows/test.yml
CHANGELOG.md
README.md
__tests__/FormField.test.js
__tests__/NumericInput.behavior.test.js
__tests__/__snapshots__/FormField.test.js.snap
__tests__/__snapshots__/TextArea.test.js.snap
package.json
source/components/FormField.js
source/components/Input.js
source/skins/simple/FormFieldSkin.js
source/skins/simple/InputSkin.js
source/skins/simple/OptionsSkin.js
source/skins/simple/PasswordInputSkin.js
source/themes/simple/SimplePasswordInput.scss
source/utils/hooks.js
stories/Input.stories.js

This PR improves the configurability of the `Input` and `FormField` components to support:
1. Showing form field error on hover
2. Showing form field error on focus
3. Styling the form field errors differently via injected css variables
which is required by https://github.com/input-output-hk/daedalus/pull/2506
❗**next release must increase major version**
- `FormField` now shows errors on hover and focus by default which can be configured via two new props:
```ts
isShowingErrorOnFocus: boolean,
isShowingErrorOnHover: boolean,
```
❗This means that we need to check all form elements (input, select, autocomplete, etc.)
- Added Github workflow for automated testing 🎉

[DDW-595] Improve input popover handling
