- CHANGELOG.md
- source/components/NumericInput.js
- stories/NumericInput.stories.js
This PR introduces a fix for react-polymorph numeric input component caret positioning.
> Fix/daef 256 React-polymorph numeric input component caret positioning issue

- CHANGELOG.md
- source/themes/simple/SimpleButton.scss
- source/themes/simple/SimpleFormField.scss
- source/themes/simple/SimpleInput.scss
- source/themes/simple/SimpleSelect.scss
- source/themes/simple/SimpleTextArea.scss
- source/themes/simple/_theme.scss
- source/themes/simple/mixins/arrow.scss
This PR updates simple theme to latest Daedalus design specs.
> Fix/daef 267 Adjust react-polymorph simple theme to match latest design specs

- CHANGELOG.md
- source/components/NumericInput.js
This PR introduces fix for caret positioning bug on NumericInput component re-render.
> Fix/daef 374 Numeric input component caret position bug

- CHANGELOG.md
- source/components/Select.js
- source/themes/simple/SimpleSelect.scss
- source/themes/simple/mixins/arrow.scss
This PR extends simple-theme default options and styling options for Simple Select component.
> Fix/daef 487 Improve react-polymorph simple-select component

- CHANGELOG.md
- source/components/Autocomplete.js
- source/components/Options.js
- source/components/Select.js
- source/skins/simple/OptionsSkin.js
- source/skins/simple/identifiers.js
- source/skins/simple/raw/AutocompleteSkin.js
- source/skins/simple/raw/OptionsSkin.js
- source/skins/simple/raw/SelectSkin.js
- source/themes/simple/SimpleAutocomplete.scss
- source/themes/simple/SimpleOptions.scss
- source/themes/simple/SimpleSelect.scss
- stories/Autocomplete.stories.js
- stories/Options.stories.js
- stories/Select.stories.js
- stories/Select.stories.scss
- stories/index.js
This PR introduces extracted options component.
> Feature/daef 519 Extract options component in React-polymorph

- CHANGELOG.md
- source/components/Button.js
- source/components/Checkbox.js
- source/components/FormField.js
- source/components/Input.js
- source/components/Modal.js
- source/components/NumericInput.js
- source/components/Options.js
- source/components/Select.js
- source/skins/simple/AutocompleteSkin.js
- source/skins/simple/ButtonSkin.js
- source/skins/simple/CheckboxSkin.js
- source/skins/simple/FormFieldSkin.js
- source/skins/simple/InputSkin.js
- source/skins/simple/ModalSkin.js
- source/skins/simple/OptionsSkin.js
- source/skins/simple/SelectSkin.js
- source/skins/simple/SwitchSkin.js
- source/skins/simple/TextAreaSkin.js
- source/skins/simple/TogglerSkin.js
- source/skins/simple/raw/AutocompleteSkin.js
- source/skins/simple/raw/OptionsSkin.js
- source/themes/simple/SimpleAutocomplete.scss
- stories/Options.stories.js
This PR introduces the following:
- New property `noResultsMessage` on Options component
- Fixed JS errors thrown upon keyboard events in Options component when there are no results to be shown
- Styling update for Autocomplete component
- Code cleanup and standardization
> Add noResultsMessage to Options component, Code cleanup

- CHANGELOG.md
- source/components/Autocomplete.js
- source/components/Modal.js
- source/components/Options.js
- source/components/Select.js
- source/components/TextArea.js
- source/skins/simple/raw/AutocompleteSkin.js
- source/skins/simple/raw/OptionsSkin.js
- stories/Autocomplete.stories.js
- stories/Autocomplete.stories.scss
This PR introduces a fix for broken `isOpeningUpward` feature on Options component.
A fix includes smarter way of positioning which is now more universal. Also, a new story for Autocomplete with `isOpeningUpward` property is added.
> Fix/daef 535 Fix React-polymorph Options component's `isOpeningUpward` feature

- CHANGELOG.md
- source/components/Options.js
- source/themes/simple/SimpleTextArea.scss
This PR introduces a fix for wrong window resize event handling in `Options` component and adds a minor CSS improvement to `Textarea` component.
> Fix/ddw 110 Fix Options component window resize event handling

- CHANGELOG.md
- source/components/Options.js
- source/skins/simple/OptionsSkin.js
- source/skins/simple/SelectSkin.js
- source/themes/simple/SimpleOptions.scss
This PR is a port of #54 for the render-props fork.
> Feature/ddw 225 Show checkmark for selected option [FORK]

- CHANGELOG.md
- package.json
This PR just refactors npm scripts to colon style to keep the setup in sync with Daedalus.
> [DDW-334] refactor npm scripts to colon style

- CHANGELOG.md
- source/components/layout/Gutter.js
- source/themes/API/gutter.js
- source/themes/API/index.js
- source/themes/simple/SimpleGutter.scss
- source/themes/simple/index.js
- source/utils/props.js
This PR adds Gutter to the layout components which offers a reusable and simple padding solution to layouts.
> [DDW-197] create gutter layout component

- CHANGELOG.md
- package.json
Adds Tomislav Horaček to contributors in `package.json`. 😄
> Updates Contributors in package.json

- LICENSE NOTICE
This PR introduces additional LICENSE NOTICE for Apache 2.0 license as is required by https://docs.google.com/document/d/1V93Qk_rFGMTRdZWcJid4jWZ4iRwNp8bZ_2J2NRydEWo/edit
- check already included LICENSE file https://github.com/input-output-hk/react-polymorph/blob/chore/ddw-753-licensing-update/LICENSE
- check newly added LICENSE NOTICE https://github.com/input-output-hk/react-polymorph/blob/chore/ddw-753-licensing-update/LICENSE%20NOTICE
> [DDW-753] Licensing update

- .eslintrc
- .flowconfig
- CHANGELOG.md
- source/components/Link.js
- source/components/NumericInput.js
- source/components/index.js
- source/skins/simple/DropdownSkin.js
- source/skins/simple/LinkSkin.js
- source/skins/simple/index.js
- source/themes/API/index.js
- source/themes/API/link.js
- source/themes/simple/SimpleLink.scss
- source/themes/simple/assets/link-ic.svg
- source/themes/simple/index.js
- stories/Dropdown.stories.js
- stories/Link.stories.js
- stories/Link.stories.scss
- stories/ThemeProvider.stories.js
- stories/index.js
- stories/theme-customizations/Link.custom.scss
- stories/theme-customizations/assets/link-ic.svg
- stories/theme-overrides/customLink.scss
This PR introduces a new "Link" component.
> [DDW-924] Create "Link" component

- CHANGELOG.md
- package.json
- scripts/prepare-sass-files-for-publishing.js
The `0.9.2` release includes the creation of and integration of the new `ScrollBar` component. It also refactors all snapshot tests to use enzyme for full DOM node rendering.
> 0.9.2 release

- source/components/PopOver.js
- source/skins/simple/PopOverSkin.js
Added className prop for custom styling on popover container.
> [DDW-550] Add className prop

- CHANGELOG.md
- source/themes/simple/SimpleOptions.scss
This PR fixes a wrong variable name for the select search highlight color
> [DDW-646] Fix select search highlight css variable

- package.json
- source/skins/simple/OptionsSkin.js
This PR updates react-polymorph and implement the search style variables.
Fixes: 
- When searching for special characters, as “.” no highlight is displayed.
---
- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
---
> [DDW-645] Update react-polymorph and implement the search style variables

- README.md
- package.json
This PR simply adds documentation and utility scripts for the upcoming release management.
> Document new release management

- CHANGELOG.md
- source/components/Options.js
This PR implements the following improvement and fix to the Select search:
* Clear the search result when selecting an option
* Fixes wrong option checkmark when searching
**Correct checkmark when searching:**
> [DDW-662] Fixes React Polymorph Select search issues

- package.json
- source/themes/simple/SimpleLink.scss
- source/themes/simple/assets/link-ic.svg
- stories/theme-overrides/customLink.scss
This PR updates the svg icon, and styling on the `Link` component
> [DDW-774] Unify external link UX
